os: Visual Studio 2017

build_script:
  - cmd: echo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" >> msbuild.rsp
  - cmd: mkdir %TEMP%\packages || echo Local packages directory already exists
  - cmd: mkdir out
  - cmd: msbuild src\corebuild.nuproj /t:restore
  - cmd: msbuild tools\CoreBuild.Tools.sln /t:restore
  - cmd: msbuild src\corebuild.nuproj /p:PackageOutputPath=%cd%\out
  - cmd: msbuild tools\CoreBuild.Tools.sln /p:PackageOutputPath=%cd%\out

nuget:
  project_feed: true
  disable_publish_on_pr: false

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      branch: master
  
artifacts:
  - path: 'out\*.nupkg'
    name: Package